### ISSUE TITLE
Allow defining SQLite3 location

### ISSUE THREAD

**Issue by amarvin** [muatik/flask-profiler#113]
Would be great if the location of the SQLite3 database file could be configured. I tried by setting

```python
app.config["flask_profiler"]["storage"]["engine] = "sqlite:////absolute_path_to_flask_profiler.sql"  # e.g. "sqlite:////var/lib/profiler/flask_profiler.sql"
```

but I get this error traceback:

```python
Traceback (most recent call last):
  File "/app/.local/lib/python3.8/site-packages/flask_profiler/storage/__init__.py", line 47, in getCollection
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1014, in _gcd_import
  File "", line 991, in _find_and_load
  File "", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sqlite:////var/lib/profiler/flask_profiler'
```

My use case is that the directory `/var/lib/profiler/` is an Azure PersistentVolume, so that my `flask_profiler` data isn't cleared with every app deploy.

**Comment by amarvin** [comment]
Nevermind, I found the correct option to configure from https://github.com/muatik/flask-profiler#sqlite.

```python
app.config["flask_profiler"]["storage"] = {
  "engine": "sqlite",
  "FILE": "/absolute_path_to_flask_profiler.sql",
}
```
