### ISSUE TITLE
ValueError: Empty module name

### ISSUE THREAD

**Issue by unkalyan** [muatik/flask-profiler#129]
Hitting this exception on python 3.9, any clues?

```
Traceback (most recent call last):
  File "/Users/xxxxxx/.pyenv/versions/3.9.0/envs/xxxxxx/lib/python3.9/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/xxxxxx/.pyenv/versions/3.9.0/envs/xxxxxx/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/Users/xxxxxx/.pyenv/versions/3.9.0/envs/xxxxxx/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/xxxxxx/.pyenv/versions/3.9.0/envs/xxxxxx/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xxxxxx/.pyenv/versions/3.9.0/envs/xxxxxx/lib/python3.9/site-packages/flask/app.py", line 1812, in full_dispatch_request
    self.ensure_sync(func)()
  File "/Users/xxxxxx/.pyenv/versions/3.9.0/envs/xxxxxx/lib/python3.9/site-packages/flask_profiler/flask_profiler.py", line 261, in init_app
    collection = storage.getCollection(CONF.get("storage", {}))
  File "/Users/xxxxxx/.pyenv/versions/3.9.0/envs/xxxxxx/lib/python3.9/site-packages/flask_profiler/storage/__init__.py", line 47, in getCollection
    module = importlib.import_module(module_name)
  File "/Users/xxxxxx/.pyenv/versions/3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1027, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _sanity_check
```

**Comment by unkalyan** [comment]
its coming as I didn't add "storage", my application doesn't have any
