### ISSUE TITLE
i get the following error: TypeError: Incorrect padding

### ISSUE THREAD

**Issue by alpayOnal** [muatik/flask-profiler#31]
2016-04-11 11:47:34 - ERROR - app: Exception on /hipchat/authorize [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_profiler/flask_profiler.py", line 112, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_profiler/flask_profiler.py", line 86, in wrapper
    raise e
TypeError: Incorrect padding

**Comment by divyenduz** [comment]
@alpayOnal : can you try the latest flask profiler code and see if this issue persists ?

**Comment by muatik** [comment]
@divyenduz I think, @alpayOnal no longer has this issue, I think because he was one of my colleagues :)

I am going to close this.
