### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by divyenduz** [muatik/flask-profiler#51]
As of now, I think python3 is not supported. I am getting the error 

```
Divyendus-MacBook-Pro:examples divyendusingh$ python3 app.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with fsevents reloader
 * Debugger is active!
Traceback (most recent call last):
  File "app.py", line 62, in <module>
    app.run(host="127.0.0.1", port=5000)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/serving.py", line 633, in run_simple
    application = DebuggedApplication(application, use_evalex)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 249, in __init__
    if self.pin is None:
  File "/usr/local/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 259, in _get_pin
    self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 159, in get_pin_and_cookie_name
    get_machine_id(),
  File "/usr/local/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 94, in get_machine_id
    _machine_id = rv = _generate()
  File "/usr/local/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 70, in _generate
    match = re.match(r'"serial-number" = <([^>]+)', dump)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object
```

I think we should be moving on to support python3 as well. Should I work on a PR adding python3 support and automating the test cases to check both python 2, python 3 support ?

Thanks

**Comment by muatik** [comment]
it is supposed to be compatible with python 3 too. Indeed, there is a test scenario for python 3: https://github.com/muatik/flask-profiler/blob/master/.travis.yml
```
python:
    - "2.7"
    - "3.4"
```

and all tests seem to be passing. probably I may forget to cover some part of the code with unit tests.

**Comment by divyenduz** [comment]
I think my error comes in example/app.py which is not supposed to be covered. This one can be closed. Thanks.
