### ISSUE TITLE
use flask-profiler in wsgi production environment

### ISSUE THREAD

**Issue by zimmerst** [muatik/flask-profiler#52]
Hi, for my flask application https://github.com/zimmerst/DmpWorkflow, i started using your brilliant profiler -- first off, thanks a lot for doing all the hard work for me. But I seem to be unable to use the flask profiler in the wsgi-production environment but only when i initialize the application by hand typing "python core/manage.py runserver"

For reference, here's the relevant code piece that includes the profiler:
```python
from DmpWorkflow.config.defaults import cfg
import flask_profiler
from DmpWorkflow import version
from socket import getfqdn
kind = cfg.get("global", "installation")

if kind == 'server':    
    from flask import Flask
    from flask.ext.mongoengine import MongoEngine
    app = Flask(__name__)
    app.config.update(LOGGER_NAME="core")
    app.config['MONGODB_DB'] = cfg.get("database", "name")
    app.config['MONGODB_USERNAME'] = cfg.get("database", "user")
    app.config['MONGODB_PASSWORD'] = cfg.get("database", "password")
    app.config['MONGODB_HOST'] = cfg.get("database", "host")
    app.config['MONGODB_PORT'] = int(cfg.get("database", "port"))
    # make connection numbers unbound
    app.config['MONGODB_MAXPOOLSIZE'] = None 
    # time out after 100ms
    app.config['MONGODB_WAITQUEUETIMEOUTMS'] = 100
    app.config["DEBUG"] = True
    app.config["flask_profiler"] = {
        "enabled": app.config["DEBUG"],
        "storage": {
            "engine": "sqlite",
            "FILE": "/tmp/flask-profiler.sql"
        },
        "basicAuth":{
            "enabled": True,
            "username": "myuser",
            "password": "mypassword"
        }
    }

    db = MongoEngine(app)
    
    def register_blueprints(app):
        # Prevents circular imports
        from DmpWorkflow.core.views import jobs
        from DmpWorkflow.core.admin import admin
        app.register_blueprint(jobs)
        app.register_blueprint(admin)
    
        if app.config['flask_profiler']['enabled']: app.logger.info("started flask profiler")
    register_blueprints(app)
    flask_profiler.init_app(app)
    
    def main():
        app.logger.info("started DmpWorkflow Server Version: %s on %s",version,getfqdn())
        app.run()
else:
    def main():
        pass

if __name__ == '__main__':
    if kind == 'server':
        main()
```

and yes, when running the wsgi application, it runs fine, except that the profiler seems to be unable to handle multiple connections to the sql database:

```bash
[Thu Nov 17 09:49:24.257431 2016] [wsgi:error] [pid 21519] started flask profiler
[Thu Nov 17 09:49:24.257440 2016] [wsgi:error] [pid 21519] --------------------------------------------------------------------------------
[Thu Nov 17 09:49:48.635678 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512] mod_wsgi (pid=21519): Exception occurred processing WSGI script '/var/www/flask_dev/workflow.wsgi'.
[Thu Nov 17 09:49:48.635867 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512] Traceback (most recent call last):
[Thu Nov 17 09:49:48.635979 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
[Thu Nov 17 09:49:48.636587 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     return self.wsgi_app(environ, start_response)
[Thu Nov 17 09:49:48.636651 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
[Thu Nov 17 09:49:48.636709 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     response = self.make_response(self.handle_exception(e))
[Thu Nov 17 09:49:48.636737 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
[Thu Nov 17 09:49:48.636828 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     reraise(exc_type, exc_value, tb)
[Thu Nov 17 09:49:48.636844 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Thu Nov 17 09:49:48.636864 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     response = self.full_dispatch_request()
[Thu Nov 17 09:49:48.636878 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Thu Nov 17 09:49:48.636898 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     rv = self.handle_user_exception(e)
[Thu Nov 17 09:49:48.636913 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Thu Nov 17 09:49:48.636932 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     reraise(exc_type, exc_value, tb)
[Thu Nov 17 09:49:48.636965 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Thu Nov 17 09:49:48.636986 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     rv = self.dispatch_request()
[Thu Nov 17 09:49:48.637000 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Thu Nov 17 09:49:48.637018 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Nov 17 09:49:48.637033 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask_profiler/flask_profiler.py", line 113, in wrapper
[Thu Nov 17 09:49:48.637121 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     return wrapped(*args, **kwargs)
[Thu Nov 17 09:49:48.637140 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask_profiler/flask_profiler.py", line 92, in wrapper
[Thu Nov 17 09:49:48.637162 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     collection.insert(measurement.__json__())
[Thu Nov 17 09:49:48.637176 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/flask_profiler/storage/sqlite.py", line 128, in insert
[Thu Nov 17 09:49:48.637288 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512]     name))
[Thu Nov 17 09:49:48.637321 2016] [wsgi:error] [pid 21519] [remote 129.194.54.242:512] OperationalError: attempt to write a readonly database
```

is there a way to make sure that the profiler can access the db for my multiple instances of the wsgi app? 
Thanks!

**Comment by VojtechBartos** [comment]
@zimmerst i had exact same issue and i have sorted it out to not using sqlite as DB for profiler in production and used mongo instead. You are already using mongo so it should be easy for you to switch

**Comment by muatik** [comment]
@zimmerst for your purpose, MongoDB or MySQL is a better choice as @VojtechBartos suggests. have you tried this yet?

**Comment by zimmerst** [comment]
Hi @muatik  & @VojtechBartos , thanks for the suggestions. My DB resides on a different host, so i have to convey all the information of mongodb to the profiler.

```python
app.config["flask_profiler"] = {
        "enabled": app.config["DEBUG"],
        "storage": {
            "engine": "mongodb",
            "MONGO_URL": "mongodb://{user}:{password}@{host}:{port}".format(user=cfg.get("database","user"), password=cfg.get("database","password"),
                                                                            host=cfg.get("database","host"), port=cfg.get("database","port")),
            "DATABASE": cfg.get("database","name"),
            "COLLECTION_NAME": "profiler"
        },
        "basicAuth":{
            "enabled": True,
            "username": "admin",
            "password": "secret"
        }
    }
```
but although the URL looks okay, following: https://docs.mongodb.com/manual/reference/connection-string/

I get an authentication error. 
```bash
[Sun Nov 20 17:46:15.270072 2016] [wsgi:error] [pid 14341] [remote 129.194.217.178:512]   File "/opt/virtualenvs/DAMPE/lib/python2.7/site-packages/pymongo/helpers.py", line 196, in _check_command_response
[Sun Nov 20 17:46:15.270384 2016] [wsgi:error] [pid 14341] [remote 129.194.217.178:512]     raise OperationFailure(msg % errmsg, code, response)
[Sun Nov 20 17:46:15.270427 2016] [wsgi:error] [pid 14341] [remote 129.194.217.178:512] OperationFailure: auth fails
```

While i try to work around this, may i suggest to add additional keywords to the mongodb storage engine (i can contribute that if you think it's helpful) to make this kind of configuration easier for a user?

Thanks!
-Stephan

**Comment by zimmerst** [comment]
actually, after a bit of playing around, i got it to work with this configuration:
```python
app.config["flask_profiler"] = {
        "enabled": app.config["DEBUG"],
        "storage": {
            "engine": "mongodb",
            "MONGO_URL": "mongodb://{user}:{password}@{host}:{port}/{db}".format(user=cfg.get("database","user"), password=cfg.get("database","password"),
                                                                                 host=cfg.get("database","host"), port=cfg.get("database","port"), db=cfg.get("database","name")),
            "DATABASE": cfg.get("database","name"),
            "COLLECTION_NAME": "profiler"
        },
        "basicAuth":{
            "enabled": True,
           ...
        }
    }
```

what i would suggest is to create the MONGO_URL based on keywords, though if you think this is clear enough, maybe it's sufficient to just add the relevant MONGO_URL example line to your documentation.
